version: '3.9'

services: 
    server:
        build: .
        ports:
            - '3001:3001'
    db:
        image: 'postgres'
        ports:
            - '5432:5432'
        environment: 
            POSTGRES_PASSWORD: '123456'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'Chronometer'